version: '3.4'

services:
  catalogdb:
   image: postgres

  basketdb:
   image: postgres

  distributedcache:
   image: redis

  orderdb:
   image: mcr.microsoft.com/mssql/server

  messagebroker:
   image: rabbitmq:management


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
    container_name: catalog.api

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    container_name: basket.api
    

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile
    container_name: discount.grpc

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile
    container_name: order.api
  
  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
    container_name: yarpapigateway

volumes:
 postgres_catalog:
 postgres_basket:
